"use client";
import React, { useEffect, useState } from "react";
import { Modal } from "../ui/modal";
import Button from "../ui/button/Button";
import { Loader } from "lucide-react";
import { invoicesApi } from "@/lib/api/invoice";


export default function ViewInvoiceModal({ isOpen, onClose, invoiceId }) {
  const [invoice, setInvoice] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (isOpen && invoiceId) {
      setLoading(true);
      invoicesApi.getInvoiceById(invoiceId).then((res) => {
        setInvoice(res.data || res);
        setLoading(false);
      });
    }
  }, [isOpen, invoiceId]);

  if (loading) return <Modal isOpen={isOpen} onClose={onClose}><Loader /></Modal>;

  return (
    <Modal isOpen={isOpen} onClose={onClose} className="max-w-[900px]">
      <div className="p-8 bg-white dark:bg-gray-900 rounded-3xl" id="printable-invoice">
        {/* Top Header */}
        <div className="flex justify-between items-start border-b pb-6 border-gray-100 dark:border-gray-800">
          <div>
            <h1 className="text-3xl font-bold text-brand-500 uppercase tracking-tighter">Madina Glass</h1>
            <p className="text-sm text-gray-500">Aluminium & Glass Works Specialist</p>
          </div>
          <div className="text-right">
            <h2 className="text-xl font-bold text-gray-800 dark:text-white">{invoice.invoiceNumber}</h2>
            <p className="text-sm text-gray-500">{new Date(invoice.createdAt).toLocaleDateString()}</p>
            <span className={`inline-block mt-2 px-3 py-1 rounded-full text-xs font-bold ${invoice.balance <= 0 ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>
              {invoice.balance <= 0 ? 'PAID' : 'UNPAID'}
            </span>
          </div>
        </div>

        {/* Customer & Staff Details */}
        <div className="grid grid-cols-2 gap-8 my-8 text-sm">
          <div>
            <h4 className="text-gray-400 uppercase font-semibold text-xs mb-2">Bill To:</h4>
            <p className="font-bold text-lg">{invoice.customer?.name}</p>
            <p className="text-gray-600">{invoice.customer?.phone}</p>
            <p className="text-gray-600 italic">{invoice.address || "No delivery address"}</p>
          </div>
          <div className="grid grid-cols-2 gap-4 bg-gray-50 dark:bg-white/5 p-4 rounded-2xl">
            <div>
              <p className="text-gray-400 text-xs">Cutter</p>
              <p className="font-medium">{invoice.cutterName || "—"}</p>
            </div>
            <div>
              <p className="text-gray-400 text-xs">Driver</p>
              <p className="font-medium">{invoice.driverName || "—"}</p>
            </div>
            <div>
              <p className="text-gray-400 text-xs">Generated By</p>
              <p className="font-medium text-brand-500">{invoice.admin?.name || "Admin"}</p>
            </div>
          </div>
        </div>

        {/* Items Table */}
        <table className="w-full text-left mb-8">
          <thead>
            <tr className="border-b dark:border-gray-800 text-xs text-gray-400 uppercase">
              <th className="py-3">Item Description</th>
              <th className="py-3">Size (WxH)</th>
              <th className="py-3">Qty</th>
              <th className="py-3">Total Sqft</th>
              <th className="py-3">Rate</th>
              <th className="py-3 text-right">Value</th>
            </tr>
          </thead>
          <tbody className="text-sm">
            {invoice.items?.map((item: any, i: number) => (
              <tr key={i} className="border-b border-gray-50 dark:border-gray-800">
                <td className="py-4 font-medium">{item.itemName}</td>
                <td className="py-4 text-gray-500">{item.width}" × {item.height}"</td>
                <td className="py-4">{item.qtyPcs}</td>
                <td className="py-4 font-mono">{item.totalSqft}</td>
                <td className="py-4">Rs. {item.rate}</td>
                <td className="py-4 text-right font-bold">Rs. {item.value.toLocaleString()}</td>
              </tr>
            ))}
          </tbody>
        </table>

        {/* Summary */}
        <div className="flex justify-end">
          <div className="w-64 space-y-3">
            <div className="flex justify-between text-gray-500">
              <span>Carriage:</span>
              <span>Rs. {invoice.carriage}</span>
            </div>
            <div className="flex justify-between text-red-500">
              <span>Discount:</span>
              <span>- Rs. {invoice.discount}</span>
            </div>
            <div className="flex justify-between text-xl font-bold pt-3 border-t">
              <span>Total:</span>
              <span className="text-brand-500">Rs. {invoice.billValue.toLocaleString()}</span>
            </div>
            <div className="flex justify-between text-sm text-green-600 font-medium">
              <span>Paid:</span>
              <span>Rs. {invoice.paidAmount}</span>
            </div>
            <div className={`flex justify-between p-3 rounded-xl font-bold ${invoice.balance > 0 ? 'bg-red-50 text-red-600' : 'bg-green-50 text-green-600'}`}>
              <span>Balance:</span>
              <span>Rs. {invoice.balance.toLocaleString()}</span>
            </div>
          </div>
        </div>

        {/* Action Buttons (Excluded from print) */}
        <div className="flex justify-end gap-3 mt-8 pt-6 border-t print:hidden">
          <Button variant="outline" onClick={onClose}>Close</Button>
          <Button onClick={() => window.print()} className="bg-brand-500 text-white">Print Invoice</Button>
        </div>
      </div>
    </Modal>
  );
}